name: Build Openwrt img

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: 60
      minimum_runs:
        description: 'The minimum runs to keep for each workflow.'
        required: true
        default: 3
      
env:
  UPLOAD_COWTRANSFER: true
  RELEASE: true

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build for ${{ matrix.flippy_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - flippy_name: 38
            flippy_filename: Armbian_20.02.0_Aml-s9xxx_buster_5.4.50-flippy-38+o.img.xz
            flippy_url: https://github.com/mingxiaoyu/armbian_flippy/releases/download/v1.0/Armbian_20.02.0_Aml-s9xxx_buster_5.4.50-flippy-38+o.img.xz
            release_name: N1_38_Openwrt.img
          - flippy_name: 55
            flippy_filename: Armbian_20.10_Aml-s9xxx_buster_5.4.105-flippy-55+o.img.xz
            flippy_url: https://github.com/mingxiaoyu/armbian_flippy/releases/download/v1.0/Armbian_20.10_Aml-s9xxx_buster_5.4.105-flippy-55+o.img.xz
            release_name: N1_55_Openwrt.img
    env:
      FLIPPY_NAME: ${{ matrix.flippy_name }}   
      FLIPPY_FILENAME: ${{ matrix.flippy_filename }}   
      FLIPPY_URL: ${{ matrix.flippy_url }}   
      RELEASE_NAME: ${{ matrix.release_name }}
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      run: |     
        version=$(curl -s "https://api.github.com/repos/mingxiaoyu/N1Openwrt/releases/latest" | awk -F '"' '/tag_name/{print $4}')
        
        echo "version=$version"  >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")"  >> $GITHUB_ENV
        
        sudo chmod  -R 777 /opt
        cp -r ${FLIPPY_NAME}/opt/* /opt
        
        test -d /opt/dl || mkdir -p /opt/dl
        sudo chmod  -R 777 /opt/dl
        
        cd /opt
        mkdir imgs
        
    - uses: actions/cache@v2
      id: opwenwrtcache
      with:
        path: |
          /opt/dl
        key: ${{ runner.os }}-opwenwrt-${{ env.FLIPPY_NAME }}-${{ env.version }}
            
    - name: Download
      #if: steps.opwenwrtcache.outputs.cache-hit != 'true'
      run: |
        cd /opt/dl
        
        wget  https://github.com/mingxiaoyu/N1Openwrt/releases/download/$version/openwrt-armvirt-64-default-rootfs.tar.gz
        wget ${FLIPPY_URL}
        
    - name: Check Files
      run: |
        cd /opt/dl
        ls
                
    - name: Install the package
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install xz-utils btrfs-progs gawk zip unzip curl dosfstools  uuid-runtime
        sudo -E apt-get -qq install git  git-core
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Copy files
      run: |
        cp /opt/dl/openwrt-armvirt-64-default-rootfs.tar.gz /opt/openwrt/openwrt-armvirt-64-default-rootfs.tar.gz
        cp /opt/dl/$FLIPPY_FILENAME /opt/imgs/$FLIPPY_FILENAME
              
    - name: build img
      run: |        
        cd /opt/imgs
        xz -d $FLIPPY_FILENAME
        
        sudo chmod  -R 777 /opt
        cd /opt/openwrt
             
        chmod +x mk_n1_opimg.sh
        ./mk_n1_opimg.sh
        	
    - name: xz-z
      id: xz
      run: |
        sudo chmod  -R 777 /opt
        cd /opt/openwrt/tmp 
        xz -z $RELEASE_NAME
        
        echo "::set-output name=status::success"

    - name: build Personal N1(我个人用的旁路由配置)
      if:  env.FLIPPY_NAME == '55' || contains(env.FLIPPY_NAME, '55')
      run: |
        [ -e openwrtfiles ] && mv openwrtfiles /opt/openwrt/files/openwrtfiles
        cd /opt/openwrt
        sed -i 's/N1_55_Openwrt.img/N1_MXY_Openwrt.img/g' mk_n1_opimg.sh
        ./mk_n1_opimg.sh
        cd /opt/openwrt/tmp 
        xz -z N1_MXY_Openwrt.img

    - name: Create release
      if: steps.xz.outputs.status == 'success'  &&  env.RELEASE == 'true' && !cancelled()
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} / N1-Openwrt-img | 编译
        allowUpdates: true
        tag: ${{ env.version }}
        commit: main
        token: ${{ secrets.GITHUB_TOKEN   }}
        body: |
          默认IP：192.168.31.2 默认密码： password
          55+o 全新刷入emmc方法：
             1. 固件刷入U盘。
             2. cd root
             3. ./install-to-emmc.sh
             4. 拔掉U盘，断电重启。
             
          55+o 在线升级方法：
             1. 上传 N1_55_Openwrt.img 到/mnt/mmcblk2p4
             2. cd /mnt/mmcblk2p4
             3. 升级脚本下载 https://raw.githubusercontent.com/mingxiaoyu/N1imagebuilder/main/55/opt/openwrt/files/update-amlogic-openwrt.sh
             4. chmod +x update-amlogic-openwrt.sh
             5. ./update-amlogic-openwrt.sh N1_55_Openwrt.img

        artifacts: "/opt/openwrt/tmp/*.xz"
                
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
