name: Build Openwrt img

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: 60
      minimum_runs:
        description: 'The minimum runs to keep for each workflow.'
        required: true
        default: 6
      
env:
  UPLOAD_COWTRANSFER: true
  RELEASE: true

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build for ${{ matrix.flippy_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - flippy_name: 38
            flippy_filename: Armbian_20.02.0_Aml-s9xxx_buster_5.4.50-flippy-38+o.img.xz
            release_name: N1_38_Openwrt.img
          - flippy_name: 49
            flippy_filename: Armbian_20.10_Aml-s9xxx_buster_5.4.77-flippy-49+o.img.xz
            release_name: N1_49_Openwrt.img
    env:
      FLIPPY_NAME: ${{ matrix.flippy_name }}   
      FLIPPY_FILENAME: ${{ matrix.flippy_filename }}   
      RELEASE_NAME: ${{ matrix.release_name }}
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      run: |     
        if [[ $FLIPPY_NAME = "38" ]]; 
        then
          echo "set the flippy 38+o"
          echo "FLIPPY_FILEID=${{ secrets.FLIPPY_38_FILEID }}"  >> $GITHUB_ENV
        else
          echo "set the flippy 49+o"
          echo "FLIPPY_FILEID=${{ secrets.FLIPPY_49_FILEID }}"  >> $GITHUB_ENV
        fi
        version=$(curl -s "https://api.github.com/repos/mingxiaoyu/N1Openwrt/releases/latest" | awk -F '"' '/tag_name/{print $4}')
        
        echo "version=$version"  >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")"  >> $GITHUB_ENV
        
        sudo chmod  -R 777 /opt
        cp -r ${FLIPPY_NAME}/opt/* /opt
        
        test -d /opt/dl || mkdir -p /opt/dl
        sudo chmod  -R 777 /opt/dl
        
        cd /opt
        mkdir imgs
        
    - uses: actions/cache@v2
      id: opwenwrtcache
      with:
        path: |
          /opt/dl
        key: ${{ runner.os }}-opwenwrt-${{ env.FLIPPY_NAME }}-${{ env.version }}
            
    - name: Download
      #if: steps.opwenwrtcache.outputs.cache-hit != 'true'
      run: |
        cd /opt/dl
        
        wget  https://github.com/mingxiaoyu/N1Openwrt/releases/download/$version/openwrt-armvirt-64-default-rootfs.tar.gz

        curl -L -c cookies.txt 'https://docs.google.com/uc?export=download&id='$FLIPPY_FILEID  |  sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1/p' > confirm.txt

        curl -L -b cookies.txt -o $FLIPPY_FILENAME  'https://docs.google.com/uc?export=download&id='$FLIPPY_FILEID'&confirm='$(<confirm.txt) 
    
    - name: Check Files
      run: |
        cd /opt/dl
        ls
                
    - name: Install the package
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install xz-utils btrfs-progs gawk zip unzip curl dosfstools  uuid-runtime
        sudo -E apt-get -qq install git  git-core
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Copy files
      run: |
        cp /opt/dl/openwrt-armvirt-64-default-rootfs.tar.gz /opt/openwrt/openwrt-armvirt-64-default-rootfs.tar.gz
        cp /opt/dl/$FLIPPY_FILENAME /opt/imgs/$FLIPPY_FILENAME
              
    - name: build img
      run: |
        rm -rf /opt/openwrt/tmp/${RELEASE_NAME}.xz   
        
        cd /opt/imgs
        xz -d $FLIPPY_FILENAME
        
        sudo chmod  -R 777 /opt
        cd /opt/openwrt
             
        chmod +x mk_n1_opimg.sh
        ./mk_n1_opimg.sh
        	
    - name: xz-z
      id: xz
      run: |
        sudo chmod  -R 777 /opt
        cd /opt/openwrt/tmp 
        xz -z $RELEASE_NAME
        
        echo "::set-output name=status::success"

    - name: Create release
      if: steps.xz.outputs.status == 'success'  &&  env.RELEASE == 'true' && !cancelled()
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} ðŸš€ / N1-Openwrt-img | ç¼–è¯‘
        allowUpdates: true
        tag: ${{ env.version }}
        commit: main
        token: ${{ secrets.GITHUB_TOKEN   }}
        body: |
          PHICOMM-N1-OpenWRT-Image 
        artifacts: "/opt/openwrt/tmp/*.xz"
        
    - name: Upload firmware to WeTransfer
      if: steps.xz.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress /opt/openwrt/tmp/$RELEASE_NAME.xz 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"
        
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
